//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BackOffice.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erp.BackOffice.App_GlobalResources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có Certificate trong khoảng thời gian từ: {0} đến: {1}. Vui lòng chọn lại khoảng thời gian khác..
        /// </summary>
        public static string CertificateDateError {
            get {
                return ResourceManager.GetString("CertificateDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật mã không trùng khớp.
        /// </summary>
        public static string ConfirmPassword_NotMatch {
            get {
                return ResourceManager.GetString("ConfirmPassword_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận lại mật khẩu.
        /// </summary>
        public static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn Ngày kết thúc..
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải theo định dạng: dd/mm/yyyy .
        /// </summary>
        public static string DateFormatError {
            get {
                return ResourceManager.GetString("DateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính này phải là ngày.
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trong quá trình xóa. Vui lòng thử lại, hoặc liên hệ admin hệ thống!.
        /// </summary>
        public static string DeleteUnSuccess {
            get {
                return ResourceManager.GetString("DeleteUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa mẫu tin..
        /// </summary>
        public static string DeletingError {
            get {
                return ResourceManager.GetString("DeletingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng Email.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính này phải là địa chỉ email.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ngày kết thúc&quot; phải lớn hơn hoặc bằng ngày hôm nay..
        /// </summary>
        public static string EndDateGreaterOrEqualNow {
            get {
                return ResourceManager.GetString("EndDateGreaterOrEqualNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là người lập phiếu, nên bạn không thể chỉnh sửa.
        /// </summary>
        public static string ErrorNoEditUserMaterialIssued {
            get {
                return ResourceManager.GetString("ErrorNoEditUserMaterialIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không phải là người lập phiếu, nên bạn không thể thêm mới vật tư.
        /// </summary>
        public static string ErrorNoNewUserMaterialIssued {
            get {
                return ResourceManager.GetString("ErrorNoNewUserMaterialIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        public static string InsertUnsucess {
            get {
                return ResourceManager.GetString("InsertUnsucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nhập vào phải là số nguyên dương..
        /// </summary>
        public static string IntegerError {
            get {
                return ResourceManager.GetString("IntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong phiếu xuất không có vật tư này.
        /// </summary>
        public static string IssuedNoMaterial {
            get {
                return ResourceManager.GetString("IssuedNoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư đã cập nhật vào kho, không thể sửa thông tin phiếu xuất được. Bạn cần xóa hết vật tư trong phiếu xuất mới có thể chỉnh sửa.
        /// </summary>
        public static string MaterialIntoWarehouseNoEditReceived {
            get {
                return ResourceManager.GetString("MaterialIntoWarehouseNoEditReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xuất vật tư.
        /// </summary>
        public static string MaterialNoIssued {
            get {
                return ResourceManager.GetString("MaterialNoIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có vật tư trong kho.
        /// </summary>
        public static string MaterialNotWarehouse {
            get {
                return ResourceManager.GetString("MaterialNotWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng vật tư trong kho không đủ, không thể thêm vật tư vào phiếu xuất.
        /// </summary>
        public static string MaterialWarehouseNo {
            get {
                return ResourceManager.GetString("MaterialWarehouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu sửa chữa đã duyệt, không thể xóa được !.
        /// </summary>
        public static string NoDeleteBrowser {
            get {
                return ResourceManager.GetString("NoDeleteBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần xóa hết chi tiết yêu cầu sửa chữa mới có thể xóa yêu cầu sửa chữa.
        /// </summary>
        public static string NoDeleteRequest {
            get {
                return ResourceManager.GetString("NoDeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn phòng cần sửa chữa. Không thể thêm mới.
        /// </summary>
        public static string NoErpRoom {
            get {
                return ResourceManager.GetString("NoErpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có phòng cần sửa chữa trong yêu cầu. Nên bạn không thể gửi yêu cầu.
        /// </summary>
        public static string NoErpRoomNoSendRequest {
            get {
                return ResourceManager.GetString("NoErpRoomNoSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đã duyệt, không thể hủy yêu cầu.
        /// </summary>
        public static string NoRequest {
            get {
                return ResourceManager.GetString("NoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn 0.
        /// </summary>
        public static string NumberError {
            get {
                return ResourceManager.GetString("NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn 1.
        /// </summary>
        public static string NumberError1 {
            get {
                return ResourceManager.GetString("NumberError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải có ít nhất {2} ký tự..
        /// </summary>
        public static string Password_LengthError {
            get {
                return ResourceManager.GetString("Password_LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập Mật mã.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng vật tư lớn hơn số lượng vật tư còn lại của phiếu xuất. Không thể thêm vật tư !!!.
        /// </summary>
        public static string QuantityMaxNoRequest {
            get {
                return ResourceManager.GetString("QuantityMaxNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải nằm trong khoảng {1} - {2}.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa! Vì hạng mục này đang được sử dụng bởi những tiến trình khác!.
        /// </summary>
        public static string RelationError {
            get {
                return ResourceManager.GetString("RelationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đã bị hủy, không thể duyệt yêu cầu này nữa.
        /// </summary>
        public static string RequestCancelNoBrowser {
            get {
                return ResourceManager.GetString("RequestCancelNoBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có ít nhất 2 đáp án.
        /// </summary>
        public static string Required2Answers {
            get {
                return ResourceManager.GetString("Required2Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có ít nhất 2 đáp án và có ít nhất 1 đáp án đúng..
        /// </summary>
        public static string RequiredAnswer {
            get {
                return ResourceManager.GetString("RequiredAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bạn cần nhập giá trị &lt;=100.
        /// </summary>
        public static string RequiredValid {
            get {
                return ResourceManager.GetString("RequiredValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn  ít nhất 1 item..
        /// </summary>
        public static string RequireItemSelection {
            get {
                return ResourceManager.GetString("RequireItemSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải upload file..
        /// </summary>
        public static string RequireUpload {
            get {
                return ResourceManager.GetString("RequireUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu thành công. .
        /// </summary>
        public static string Save_Succeeded {
            get {
                return ResourceManager.GetString("Save_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước ảnh không được vượt quá 50MB..
        /// </summary>
        public static string SizeImgError {
            get {
                return ResourceManager.GetString("SizeImgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} ký tự..
        /// </summary>
        public static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi vượt quá {0} ký tự.
        /// </summary>
        public static string StringTooLongError {
            get {
                return ResourceManager.GetString("StringTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn sửa chữa chưa hoàn thành, không thể thêm vật tư.
        /// </summary>
        public static string SuccessNoMaterialNew {
            get {
                return ResourceManager.GetString("SuccessNoMaterialNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc không được nhỏ hơn Giờ bắt đầu.
        /// </summary>
        public static string TimeError {
            get {
                return ResourceManager.GetString("TimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch thi của tuần này đã tồn tại, hãy chọn tuần khác..
        /// </summary>
        public static string TrainingScheduleExisted {
            get {
                return ResourceManager.GetString("TrainingScheduleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công..
        /// </summary>
        public static string UpdateUnsuccess {
            get {
                return ResourceManager.GetString("UpdateUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng Url.
        /// </summary>
        public static string UrlError {
            get {
                return ResourceManager.GetString("UrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập Tên đăng nhập.
        /// </summary>
        public static string Username_Required {
            get {
                return ResourceManager.GetString("Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số người thắng, số điểm tối thiểu, điểm thêm cho đợt rút thăm..
        /// </summary>
        public static string ValidCheckCloseLottery {
            get {
                return ResourceManager.GetString("ValidCheckCloseLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không hợp lệ.
        /// </summary>
        public static string ValueInvalid {
            get {
                return ResourceManager.GetString("ValueInvalid", resourceCulture);
            }
        }
    }
}
